// Generated by CoffeeScript 2.5.1
(function() {
    // Copyright (c) 2020 Alexander Sporn. All rights reserved.

  var Enocean, client, config, enocean, mqtt;

  config = require('./config.json');

  mqtt = require('mqtt');

  Enocean = require('./Enocean');

  enocean = new Enocean({
    port: config.port
  });

  client = mqtt.connect(config.mqtt, {
    username: config.mqtt_username,
    password: config.mqtt_password,
    keepalive: 3600
  });

  enocean.on('pressed', (sender, button) => {
    console.log(`enocean/${sender}` + " - " + JSON.stringify({
      type: button
    }));
    return client.publish(`enocean/${sender}`, JSON.stringify({
      type: button
    }));
  });

  client.on('connect', function(packet) {
    if (packet.returnCode === 0) {
      return console.log(`Connected to ${config.mqtt}`);
    } else {
      console.log(`Connack error ${packet.returnCode}`);
      return process.exit(1);
    }
  });

  client.on('reconnect', function() {
    return console.log("Reconnecting");
  });

  client.on('close', function() {
    return console.log("Connection closed");
  });

  client.on('error', function(e) {
    console.log(`Error ${e}`);
    return process.exit(1);
  });

}).call(this);
